addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"             % "1.1.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"                 % "2.0.7")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                       % "0.2.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"                   % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.13.0")